// Record names should be in the *lowest* group they can belong in.
export default {
  record: $ => choice(
    $.account,
    $.achaddenda,
    $.achaddinfo,
    $.achedit,
    $.achitem,
    $.activity,
    $.agreement,
    $.atmdialog,
    $.batchachorig,
    $.card,
    $.cashletter,
    $.cashorder,
    $.cdmdialog,
    $.check,
    $.collateral,
    $.corptransfer,
    $.cpworkcard,
    $.credrep,
    $.ctr,
    $.ctraccount,
    $.ctrbranch,
    $.ctrforeign,
    $.ctrperson,
    $.dealer,
    $.eft,
    $.excpaddenda,
    $.excpaddinfo,
    $.excpitem,
    $.externalaccount,
    $.externalloan,
    $.glaccount,
    $.glentry,
    $.glsubaccount,
    $.gltran,
    $.household,
    $.inventory,
    $.invoice,
    $.irs,
    $.loanapp,
    $.lookup,
    $.mbraddress,
    $.memberrec,
    $.nonacctname,
    $.participant,
    $.participation,
    $.participationloan,
    $.payee,
    $.portfolio,
    $.preference,
    $.receiveditem,
    $.remittance,
    $.reserveplan,
    $.share,
    $.site,
    $.user,
    $.vendor,
    $.westernunion,
    $.wire,
    $.worklistedit,

    // Subrecord exceptions
    $.comment,
    $.fmhistory,
    $.glhistory,
    $.loan,
    $.name,
    $.note,
    $.tracking
  ),
  account: $ => /account/i,
  achaddenda: $ => /achaddenda/i,
  achaddinfo: $ => /achaddinfo/i,
  achedit: $ => /achedit/i,
  achitem: $ => /achitem/i,
  activity: $ => /activity/i,
  agreement: $ => /agreement/i,
  atmdialog: $ => /atmdialog/i,
  batchachorig: $ => /batchachorig/i,
  card: $ => /card/i,
  cashletter: $ => /cashletter/i,
  cashorder: $ => /cashorder/i,
  cdmdialog: $ => /cdmdialog/i,
  check: $ => /check/i,
  collateral: $ => /collateral/i,
  corptransfer: $ => /corptransfer/i,
  cpworkcard: $ => /cpworkcard/i,
  credrep: $ => /credrep/i,
  ctr: $ => /ctr/i,
  ctraccount: $ => /ctraccount/i,
  ctrbranch: $ => /ctrbranch/i,
  ctrforeign: $ => /ctrforeign/i,
  ctrperson: $ => /ctrperson/i,
  dealer: $ => /dealer/i,
  eft: $ => choice(/eft/i, /bill/i, /payroll/i),
  excpaddenda: $ => /excpaddenda/i,
  excpaddinfo: $ => /excpaddinfo/i,
  excpitem: $ => /excpitem/i,
  externalaccount: $ => /externalaccount/i,
  externalloan: $ => /externalloan/i,
  glaccount: $ => /glaccount/i,
  glentry: $ => /glentry/i,
  glsubaccount: $ => /glsubaccount/i,
  gltran: $ => /gltran/i,
  household: $ => /household/i,
  inventory: $ => /inventory/i,
  invoice: $ => /invoice/i,
  irs: $ => /irs/i,
  loanapp: $ => /loanapp/i,
  lookup: $ => /lookup/i,
  mbraddress: $ => /mbraddress/i,
  memberrec: $ => /memberrec/i,
  nonacctname: $ => /nonacctname/i,
  participant: $ => /participant/i,
  participation: $ => choice(/participation/i, /pool/i),
  participationloan: $ => choice(/participationloan/i, /poolloan/i),
  payee: $ => /payee/i,
  portfolio: $ => /portfolio/i,
  preference: $ => /preference/i,
  receiveditem: $ => /receiveditem/i,
  remittance: $ => /remittance/i,
  reserveplan: $ => /reserveplan/i,
  share: $ => choice(/share/i, /savings/i),
  site: $ => /site/i,
  user: $ => /user/i,
  vendor: $ => /vendor/i,
  westernunion: $ => /westernunion/i,
  wire: $ => /wire/i,
  worklistedit: $ => /worklistedit/i,

  subrecord: $ => choice(
    $.access,
    $.addendainfo,
    $.analysis,
    $.analysisgroup,
    $.analysisplan,
    $.bankruptcy,
    $.beneficiaryadv,
    $.beneficiaryfiadv,
    $.beneficiaryfiinfo,
    $.beneficiaryinfo,
    $.cashordertype,
    $.checkorder,
    $.collhold,
    $.comment, // Can also be used at the record level; implies $.account as record
    $.ctrtraninfo,
    $.distribution,
    $.document,
    $.drawdowndebitacctadv,
    $.escrow,
    $.escrowanalysis,
    $.finance,
    $.fitofiinfo,
    $.fmhistory, // Can also be used at the record level.
    $.glhistory, // Can also be used at the record level; implies $.glaccount as record
    $.hold,
    $.intermedfiadv,
    $.imtermedfiinfo,
    $.item,
    $.lnsegment,
    $.loan,// Can also be used at the record level.
    $.name, // Can also be used at the record level.
    $.note, // Can also be used at the record level.
    $.ofacdetails,
    $.person,
    $.pledge,
    $.receiverfiinfo,
    $.servicemessage,
    $.schedule,
    $.tracking, // Can also be used at the record level.
    $.transaction,
    $.transfer,
    $.uscauditinfo,
    $.worklistfield,
  ),
  access: $ => /access/i,
  addendainfo: $ => /addendainfo/i,
  analysis: $ => /analysis/i,
  analysisgroup: $ => /analysisgroup/i,
  analysisplan: $ => /analysisplan/i,
  bankruptcy: $ => /bankruptcy/i,
  beneficiaryadv: $ => /beneficiaryadv/i,
  beneficiaryfiadv: $ => /beneficiaryfiadv/i,
  beneficiaryfiinfo: $ => /beneficiaryfiinfo/i,
  beneficiaryinfo: $ => /beneficiaryinfo/i,
  cashordertype: $ => /cashordertype/i,
  checkorder: $ => /checkorder/i,
  collhold: $ => /collhold/i,
  comment: $ => /comment/i,
  ctrtraninfo: $ => /ctrtraninfo/i,
  distribution: $ => /distribution/i,
  document: $ => /document/i,
  drawdowndebitacctadv: $ => /drawdowndebitacctadv/i,
  escrow: $ => /escrow/i,
  escrowanalysis: $ => /escrowanalysis/i,
  finance: $ => /finance/i,
  fitofiinfo: $ => /fitofiinfo/i,
  fmhistory: $ => /fmhistory/i, // Can also be used at the record level; implies $.account as record
  glhistory: $ => /glhistory/i, // Can also be used at the record level; implies $.glaccount as record
  hold: $ => /hold/i,
  intermedfiadv: $ => /intermedfiadv/i,
  imtermedfiinfo: $ => /imtermedfiinfo/i,
  item: $ => /item/i,
  lnsegment: $ => /lnsegment/i,
  loan: $ => /loan/i,// Can also be used at the record level.
  name: $ => /name/i, // Can also be used at the record level.
  note: $ => /note/i, // Can also be used at the record level.
  ofacdetails: $ => /ofacdetails/i,
  person: $ => /person/i,
  pledge: $ => /pledge/i,
  receiverfiinfo: $ => /receiverfiinfo/i,
  servicemessage: $ => /servicemessage/i,
  schedule: $ => /schedule/i,
  tracking: $ => /tracking/i, // Can also be used at the record level.
  transaction: $ => /transaction/i,
  transfer: $ => /transfer/i,
  uscauditinfo: $ => /uscauditinfo/i,
  worklistfield: $ => /worklistfield/i,

  bottomrecord: $ => choice($.prepetitionbal),
  prepetitionbal: $ => /prepetitionbal/i,
};
